BB_Globals = {}
local BB = BB_Globals

BB.BB_default = {
	["MacroName"] = "BuffBlock",
	["Buffs"] = {}
}
BB.DEFAULT_ICON = "INV_MISC_QUESTIONMARK";
BB.BuffBlockMenuStrings = {
   battleshout = "Battle Shout",
   blessingofsalvation = "Blessing of Salvation",
   greaterblessingofsalvation = "Greater Blessing of Salvation",
   blessingoflight = "Blessing of Light",
   greaterblessingoflight = "Greater Blessing of Light",
   blessingofsanctuary = "Blessing of Sanctuary",
   greaterblessingofsanctuary = "Greater Blessing of Sanctuary",
   blessingofmight = "Blessing of Might",
   greaterblessingofmight = "Greater Blessing of Might",
   thorns = "Thorns",
   bloodthirst = "Bloodthirst",
   divinespirit = "Divine Spirit",
   prayerofspirit = "Prayer of Spirit",
   arcaneintellect = "Arcane Intellect",
   arcanebrilliance = "Arcane Brilliance",
   blessingofprotection = "Blessing of Protection",
   abolishpoison = "Abolish Poison",
   abolishdisease = "Abolish Disease",
   renew = "Renew",
   rejuvenation = "Rejuvenation",
   regrowth = "Regrowth",
   inspiration = "Inspiration",
   divineintervention = "Divine Intervention",
   detectgreaterinvisiblity = "Detect Greater Invisibility",
   unendingbreath = "Unending Breath",
   layonhands = "Lay on Hands",
   prayerofshadowprotection = "Prayer of Shadow Protection",
   fireshield = "Fire Shield",
   dampenmagic = "Dampen Magic",
   amplifymagic = "Amplify magic",
};